name: CI

on:
  pull_request: {}
  push:
    branches:
    - master
    tags:
    - "*"

jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
    - name: git co
      uses: actions/checkout@v1
    - name: checkout actions
      id: checkout
      uses: ./.github/actions/checkout
      with:
        github-context: ${{ toJson(github) }}
    - name: test git
      run: |
        git status
        git log -n 4
